import { Playfair_Display, Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import FooterCTA from "@/components/common/FooterCTA";
import Instagram from "@/components/Instagram";
import Cart from "@/components/Cart";

const playfair = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["500"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata = {
  title: "Forside - Moons by Mogens Gyldenløve",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${lato.variable} antialiased`}>
        <Header />
        {children}
        <Instagram />
        <FooterCTA />
        <Footer />
        <Cart />
      </body>
    </html>
  );
}
